name: CI

on:
  push:
    branches: [main]
  workflow_dispatch:

jobs:
  compromised-ci:
    runs-on: ubuntu-latest
    env:
      SECRET_TOKEN: ${{ secrets.SECRET_TOKEN }}  # <-- secret réel du repo

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 18

      - name: Install dependencies
        working-directory: ./web-app
        run: npm install
